name: Engine

on:
  push:
    branches: ["**"]
    paths:
      - "core-engine/**"
      - "services/**"
      - "config/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - ".github/workflows/engine.yml"
  pull_request:
    branches: ["**"]
    paths:
      - "core-engine/**"
      - "services/**"
      - "config/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - ".github/workflows/engine.yml"
  workflow_dispatch:

concurrency:
  group: engine-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-Dwarnings"
  NODE_VERSION: "20"
  PYTHON_VERSION: "3.12"
  SOLANA_VERSION: "v1.18.26"
  # Optional: match your repo's minimum supported Rust version policy
  # MSRV: "1.78.0"

jobs:
  rust-core:
    name: Rust core-engine (fmt, clippy, test)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OS deps
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential pkg-config libssl-dev libudev-dev \
            curl ca-certificates git jq
          sudo rm -rf /var/lib/apt/lists/*

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Cargo fmt (check)
        run: |
          set -euo pipefail
          cargo fmt --all --check

      - name: Cargo clippy (deny warnings)
        run: |
          set -euo pipefail
          cargo clippy --workspace --all-targets --all-features

      - name: Cargo tests (workspace)
        run: |
          set -euo pipefail
          cargo test --workspace --all-features

      - name: Cargo doc (no deps)
        run: |
          set -euo pipefail
          cargo doc --workspace --no-deps

  integration-localnet:
    name: Engine integration (local Solana + smoke)
    runs-on: ubuntu-latest
    needs: rust-core
    defaults:
      run:
        shell: bash
    env:
      SOLANA_URL: "http://127.0.0.1:8899"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OS deps
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential pkg-config libssl-dev libudev-dev \
            curl ca-certificates git jq unzip
          sudo rm -rf /var/lib/apt/lists/*

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Install Solana CLI
        run: |
          set -euo pipefail
          echo "Installing Solana $SOLANA_VERSION"
          sh -c "$(curl -sSfL https://release.solana.com/${SOLANA_VERSION}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
          solana --version

      - name: Configure Solana URL
        run: |
          set -euo pipefail
          solana config set --url "$SOLANA_URL"
          solana config get

      - name: Prepare wallet
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.config/solana"
          solana-keygen new --no-bip39-passphrase -o "$HOME/.config/solana/id.json" --force
          echo "SOLANA_WALLET=$HOME/.config/solana/id.json" >> "$GITHUB_ENV"
          echo "SOLANA_URL=$SOLANA_URL" >> "$GITHUB_ENV"
          solana address

      - name: Start local validator
        run: |
          set -euo pipefail
          solana-test-validator --reset --quiet --limit-ledger-size &
          echo $! > /tmp/validator.pid

          for i in $(seq 1 60); do
            if solana cluster-version >/dev/null 2>&1; then
              echo "Validator is up"
              break
            fi
            sleep 1
          done

      - name: Airdrop
        run: |
          set -euo pipefail
          solana airdrop 10 || solana airdrop 10
          solana balance

      - name: Build engine binaries
        run: |
          set -euo pipefail
          # Build only engine-related bins if present; fall back to workspace build.
          if cargo metadata --no-deps --format-version 1 | jq
